# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stm_samp <- function(theta, x, K) {
    .Call(`_elogitR_stm_samp`, theta, x, K)
}

elpatterns <- function(K, Kmax) {
    .Call(`_elogitR_elpatterns`, K, Kmax)
}

flpatterns <- function(K) {
    .Call(`_elogitR_flpatterns`, K)
}

elprofile <- function(z, theta, y, x, Kmax) {
    .Call(`_elogitR_elprofile`, z, theta, y, x, Kmax)
}

flprofile <- function(z, theta, y, x) {
    .Call(`_elogitR_flprofile`, z, theta, y, x)
}

elstm <- function(theta, y, x, Kmax, hessian) {
    .Call(`_elogitR_elstm`, theta, y, x, Kmax, hessian)
}

flstm <- function(theta, y, x, hessian) {
    .Call(`_elogitR_flstm`, theta, y, x, hessian)
}

elrsm <- function(theta, y, m, p, Kmax, hessian) {
    .Call(`_elogitR_elrsm`, theta, y, m, p, Kmax, hessian)
}

flrsm <- function(theta, y, m, p, hessian) {
    .Call(`_elogitR_flrsm`, theta, y, m, p, hessian)
}

mnl_samp <- function(theta, x, K) {
    .Call(`_elogitR_mnl_samp`, theta, x, K)
}

elmnl <- function(theta, y, x, Kmax, hessian) {
    .Call(`_elogitR_elmnl`, theta, y, x, Kmax, hessian)
}

flmnl <- function(theta, y, x, hessian) {
    .Call(`_elogitR_flmnl`, theta, y, x, hessian)
}

